[test-ssh]
user = test-ssh
group = clp
listen = /run/php/php8.3-fpm-test-ssh.sock
listen.owner = test-ssh
listen.group = clp
listen.mode = 0660

pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35

php_admin_value[error_log] = /var/log/fpm-php.test-ssh.log
php_admin_flag[log_errors] = on
php_admin_value[memory_limit] = 2G
